### ISSUE TITLE
  I'm trying to run the code of NCdemo,but reported a bug.

### ISSUE THREAD

**Issue by haibucuo0** [ArdenB/TSSRESTREND#5]
When I ran S02_TSSRESTRENDattribution.R in rstudio, bug happend.
Error in { : task 1 failed - "unused argument (returnVCRcoef = FALSE)"
Timing stopped at: 11.43 2.413 13.66.
How to solve this bug?
Thank you!!

**Comment by zerihunc** [comment]
I have faced the same problem. Can anyone help me please?
